# Generated by Django 5.2.16 on 2026-07-17 20:51

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(help_text='16 Hexadezimalzeichen; Trennzeichen werden automatisch entfernt.', max_length=16, validators=[django.core.validators.RegexValidator(message='Der DevEUI muss aus genau 16 Hexadezimalzeichen (0-9, A-F) bestehen.', regex='^[0-9A-F]{16}$')], verbose_name='DevEUI')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Hersteller')),
                ('sensor_type', models.CharField(blank=True, max_length=120, verbose_name='Typ')),
                ('serial_number', models.CharField(blank=True, max_length=120, verbose_name='Seriennummer')),
                ('note', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensoren',
                'ordering': ['dev_eui'],
                'indexes': [models.Index(fields=['tenant', 'dev_eui'], name='sensors_sen_tenant__38e109_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'dev_eui'), name='sensor_deveui_unique_per_tenant')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
