# Generated by Django 5.2.16 on 2026-07-17 22:29

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pg_trgm'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensor',
            index=django.contrib.postgres.indexes.GinIndex(fields=['dev_eui'], name='sensor_dev_eui_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
