# Generated by Django 5.2.16 on 2026-07-17 19:52

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('full_name', models.CharField(max_length=200, verbose_name='Vollständiger Name')),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('tenant_admin', 'Mandantenadministrator'), ('installer', 'Monteur')], max_length=20, verbose_name='Rolle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Angelegt am')),
                ('tenant', models.ForeignKey(blank=True, help_text='Für Superadmins leer; für alle anderen Rollen zwingend.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ['full_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('role', 'superadmin'), ('tenant__isnull', True)), models.Q(models.Q(('role', 'superadmin'), _negated=True), ('tenant__isnull', False)), _connector='OR'), name='user_tenant_matches_role')],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
