# Generated by Django 5.2.16 on 2026-07-17 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token-Hash')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Erstellt am')),
                ('expires_at', models.DateTimeField(verbose_name='Gültig bis')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Eingelöst am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_device_invites', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_invites', to='core.tenant', verbose_name='Mandant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_invites', to=settings.AUTH_USER_MODEL, verbose_name='Monteur')),
            ],
            options={
                'verbose_name': 'Geräteeinladung',
                'verbose_name_plural': 'Geräteeinladungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Bezeichnung')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token-Hash')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Registriert am')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt gesehen')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesperrt am')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.tenant', verbose_name='Mandant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Monteur')),
            ],
            options={
                'verbose_name': 'Gerät',
                'verbose_name_plural': 'Geräte',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='accounts_de_tenant__c1dbda_idx')],
            },
        ),
    ]
