# Generated by Django 5.2.16 on 2026-07-17 19:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Kürzel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('gps_accuracy_threshold_m', models.PositiveIntegerField(default=5, help_text='Ist die gemessene Genauigkeit schlechter als dieser Wert, wird der Monteur bei der Installation gewarnt.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='GPS-Genauigkeitsgrenze (Meter)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'Mandant',
                'verbose_name_plural': 'Mandanten',
                'ordering': ['name'],
            },
        ),
    ]
