# Generated by Django 5.2.16 on 2026-07-17 22:08

import apps.installations.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Client-UUID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Längengrad')),
                ('accuracy_m', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Genauigkeit (Meter)')),
                ('gps_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='GPS-Zeitstempel')),
                ('captured_at', models.DateTimeField(verbose_name='Erfasst am (Gerät)')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Empfangen am (Server)')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('installed', 'Eingebaut'), ('removed', 'Ausgebaut')], default='installed', max_length=20, verbose_name='Status')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Storniert am')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Stornogrund')),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to=settings.AUTH_USER_MODEL, verbose_name='Monteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='projects.project', verbose_name='Projekt')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='sensors.sensor', verbose_name='Sensor')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installationen',
                'ordering': ['-received_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Client-UUID')),
                ('photo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Foto-UUID')),
                ('original', models.FileField(max_length=300, upload_to=apps.installations.models._photo_upload_path, verbose_name='Original')),
                ('thumbnail', models.FileField(max_length=300, upload_to=apps.installations.models._photo_upload_path, verbose_name='Thumbnail')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Hochgeladen am')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='installations.installation', verbose_name='Installation')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Installationsfoto',
                'verbose_name_plural': 'Installationsfotos',
                'ordering': ['order', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['tenant', 'status'], name='installatio_tenant__420713_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['tenant', '-received_at'], name='installatio_tenant__f40a07_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['sensor'], name='installatio_sensor__3048df_idx'),
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['project'], name='installatio_project_e16db4_idx'),
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_uuid'), name='installation_client_uuid_unique_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True), ('status', 'installed')), fields=('sensor',), name='one_active_installation_per_sensor'),
        ),
        migrations.AddConstraint(
            model_name='installationphoto',
            constraint=models.UniqueConstraint(fields=('installation', 'client_uuid'), name='photo_client_uuid_unique_per_installation'),
        ),
    ]
