# Generated by Django 5.2.16 on 2026-07-17 22:29

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pg_trgm'),
        ('installations', '0001_initial'),
        ('projects', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='installation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='installation_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
