# Generated by Django 5.2.16 on 2026-07-17 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Zeitpunkt')),
                ('action', models.CharField(choices=[('login', 'Anmeldung'), ('login_failed', 'Fehlgeschlagene Anmeldung'), ('logout', 'Abmeldung'), ('tenant_created', 'Mandant angelegt'), ('tenant_updated', 'Mandant geändert'), ('tenant_deactivated', 'Mandant deaktiviert'), ('tenant_activated', 'Mandant aktiviert'), ('user_created', 'Benutzer angelegt'), ('user_updated', 'Benutzer geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('user_activated', 'Benutzer aktiviert')], max_length=40, verbose_name='Aktion')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Objekttyp')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Objekt-ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objektbezeichnung')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Änderungen')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.CharField(blank=True, max_length=400, verbose_name='User-Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.tenant', verbose_name='Mandant')),
            ],
            options={
                'verbose_name': 'Audit-Eintrag',
                'verbose_name_plural': 'Audit-Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['tenant', '-created_at'], name='audit_audit_tenant__1d7666_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
