# Generated by Django 5.2.16 on 2026-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('login_failed', 'Fehlgeschlagene Anmeldung'), ('logout', 'Abmeldung'), ('tenant_created', 'Mandant angelegt'), ('tenant_updated', 'Mandant geändert'), ('tenant_deactivated', 'Mandant deaktiviert'), ('tenant_activated', 'Mandant aktiviert'), ('user_created', 'Benutzer angelegt'), ('user_updated', 'Benutzer geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('user_activated', 'Benutzer aktiviert'), ('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geändert'), ('project_assigned', 'Projekt zugewiesen'), ('project_unassigned', 'Projektzuweisung entfernt'), ('sensor_created', 'Sensor angelegt'), ('sensor_updated', 'Sensor geändert'), ('sensor_deleted', 'Sensor gelöscht'), ('sensor_imported', 'Sensoren importiert')], max_length=40, verbose_name='Aktion'),
        ),
    ]
