# Generated by Django 5.2.16 on 2026-07-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Anmeldung'), ('login_failed', 'Fehlgeschlagene Anmeldung'), ('logout', 'Abmeldung'), ('tenant_created', 'Mandant angelegt'), ('tenant_updated', 'Mandant geändert'), ('tenant_deactivated', 'Mandant deaktiviert'), ('tenant_activated', 'Mandant aktiviert'), ('user_created', 'Benutzer angelegt'), ('user_updated', 'Benutzer geändert'), ('user_deactivated', 'Benutzer deaktiviert'), ('user_activated', 'Benutzer aktiviert'), ('project_created', 'Projekt angelegt'), ('project_updated', 'Projekt geändert'), ('project_assigned', 'Projekt zugewiesen'), ('project_unassigned', 'Projektzuweisung entfernt'), ('sensor_created', 'Sensor angelegt'), ('sensor_updated', 'Sensor geändert'), ('sensor_deleted', 'Sensor gelöscht'), ('sensor_imported', 'Sensoren importiert'), ('device_invite_created', 'Geräteeinladung erstellt'), ('device_invite_revoked', 'Geräteeinladung widerrufen'), ('device_registered', 'Gerät registriert'), ('device_revoked', 'Gerät gesperrt'), ('device_removed', 'Gerät entfernt'), ('installation_created', 'Installation erfasst'), ('installation_corrected', 'Installation korrigiert'), ('installation_cancelled', 'Installation storniert'), ('installation_photo_added', 'Foto hinzugefügt')], max_length=40, verbose_name='Aktion'),
        ),
    ]
